#include <ctype.h>
#include <stdio.h>
#include <string.h>

int		ft_isalpha(int c);
int		ft_isdigit(int c);
int		ft_isalnum(int c);
int		ft_isascii(int c);
int		ft_isprint(int c);
int		ft_strlen(char *s);
void	ft_memset(char	*str, char c, int n);
void	ft_bzero(char	*s, int n);
void	*ft_memcpy(char	*dst, char	*src, int	n);

int	main(void)
{
	char	*s1;
	char	*s2;
	char	*s3;
	char	*s4;
	char	*s5;
	char	*s6;
	char	*s7;
	char	*s8;
	char	*s9;
	char	*s10;
	char	*s11;
	char	*s12;
	char	*s13;
	char	*s14;

	printf ("\n~~~~~~~~~~~~~~~~~~~~\n");
	printf ("ISALPHA:\n");
	printf ("~~~~~~~~~~~~~~~~~~~~\n");
	printf ("%d\n", isalpha(101));
	printf ("%d\n\n", ft_isalpha(101));
	printf ("%d\n", isalpha(106));
	printf ("%d\n\n", ft_isalpha(106));
	printf ("%d\n", isalpha(113));
	printf ("%d\n\n", ft_isalpha(113));
	printf ("%d\n", isalpha(64));
	printf ("%d\n\n", ft_isalpha(64));
	printf ("%d\n", isalpha(32));
	printf ("%d\n", ft_isalpha(32));
	printf ("\n~~~~~~~~~~~~~~~~~~~~\n");
	printf ("ISDIGIT:\n");
	printf ("~~~~~~~~~~~~~~~~~~~~\n");
	printf ("%d\n", isdigit(47));
	printf ("%d\n\n", ft_isdigit(47));
	printf ("%d\n", isdigit(48));
	printf ("%d\n\n", ft_isdigit(48));
	printf ("%d\n", isdigit(49));
	printf ("%d\n\n", ft_isdigit(49));
	printf ("%d\n", isdigit(50));
	printf ("%d\n\n", ft_isdigit(50));
	printf ("%d\n", isdigit(55));
	printf ("%d\n\n", ft_isdigit(55));
	printf ("%d\n", isdigit(57));
	printf ("%d\n\n", ft_isdigit(57));
	printf ("%d\n", isdigit(59));
	printf ("%d\n\n", ft_isdigit(59));
	printf ("%d\n", isdigit(113));
	printf ("%d\n", ft_isdigit(113));
	printf ("\n~~~~~~~~~~~~~~~~~~~~\n");
	printf ("ISALNUM:\n");
	printf ("~~~~~~~~~~~~~~~~~~~~\n");
	printf ("%d\n", isalnum(32));
	printf ("%d\n\n", ft_isalnum(32));
	printf ("%d\n", isalnum(47));
	printf ("%d\n\n", ft_isalnum(47));
	printf ("%d\n", isalnum(48));
	printf ("%d\n\n", ft_isalnum(48));
	printf ("%d\n", isalnum(57));
	printf ("%d\n\n", ft_isalnum(57));
	printf ("%d\n", isalnum(112));
	printf ("%d\n", ft_isalnum(112));
	printf ("\n~~~~~~~~~~~~~~~~~~~~\n");
	printf ("ISASCII:\n");
	printf ("~~~~~~~~~~~~~~~~~~~~\n");
	printf ("%d\n", isascii(0));
	printf ("%d\n\n", ft_isascii(0));
	printf ("%d\n", isascii(32));
	printf ("%d\n\n", ft_isascii(32));
	printf ("%d\n", isascii(256));
	printf ("%d\n", ft_isascii(256));
	printf ("\n~~~~~~~~~~~~~~~~~~~~\n");
	printf ("ISPRINT:\n");
	printf ("~~~~~~~~~~~~~~~~~~~~\n");
	printf ("%d\n", isprint(0));
	printf ("%d\n\n", ft_isprint(0));
	printf ("%d\n", isprint(103));
	printf ("%d\n\n", ft_isprint(103));
	printf ("%d\n", isprint(127));
	printf ("%d\n\n", ft_isprint(127));
	printf ("%d\n", isprint(245));
	printf ("%d\n", ft_isprint(245));
	printf ("\n~~~~~~~~~~~~~~~~~~~~\n");
	printf ("STRLEN:\n");
	printf ("~~~~~~~~~~~~~~~~~~~~\n");
	char str1[] = "Hello, World!";
	s1 = &str1[0];
	printf ("Hello, world! = %lu\n", strlen(s1));
	printf ("Hello, world! = %d\n", ft_strlen(s1));
	char str2[] = "Hello";
	s2 = &str2[0];
	printf ("Hello = %lu\n", strlen(s2));
	printf ("Hello = %d\n", ft_strlen(s2));
	char str3[] = "World!";
	s3 = &str3[0];
	printf ("World! = %lu\n", strlen(s3));
	printf ("World! = %d\n", ft_strlen(s3));
	printf ("\n~~~~~~~~~~~~~~~~~~~~\n");
	printf ("MEMSET:\n");
	printf ("~~~~~~~~~~~~~~~~~~~~\n");
	char str4[] = "Hello, World!";
	s4 = &str4[0];
	char str5[] = "Hello, World!";
	s5 = &str5[0];
	memset(s4 + 1, '.', 3);
	ft_memset(s5 + 1, '.', 3);
	printf ("Hello, world! = %s\n", s4);
	printf ("Hello, world! = %s\n\n", s5);
	char str6[] = "I like the lady horses best.";
	s6 = &str6[0];
	char str7[] = "I like the lady horses best.";
	s7 = &str7[0];
	memset(s6 + 4, '.', 10);
	ft_memset(s7 + 4, '.', 10);
	printf ("I like the lady horses best. = %s\n", s6);
	printf ("I like the lady horses best. = %s\n", s7);
	printf ("\n~~~~~~~~~~~~~~~~~~~~\n");
	printf ("BZERO:\n");
	printf ("~~~~~~~~~~~~~~~~~~~~\n");
	char str8[] = "how they make it all look easy";
	s8 = &str8[0];
	char str9[] = "how they make it all look easy";
	s9 = &str9[0];
	bzero(s8 + 10, 3);
	ft_bzero(s9 + 10, 3);
	printf ("how they make it all look easy = %s\n", s8);
	printf ("how they make it all look easy = %s\n\n", s9);
	char str10[] = "how they make it all look easy";
	s10 = &str10[0];
	char str11[] = "how they make it all look easy";
	s11 = &str11[0];
	bzero(s10 + 1, 7);
	ft_bzero(s11 + 1, 7);
	printf ("how they make it all look easy = %s\n", s10);
	printf ("how they make it all look easy = %s\n", s11);
	printf ("\n~~~~~~~~~~~~~~~~~~~~\n");
	printf ("MEMCPY:\n");
	printf ("~~~~~~~~~~~~~~~~~~~~\n");
	char str12[] = "is as fun as taking a nap, or grass.";
	s12 = &str12[0];
	char str13[] = "I like";
	s13 = &str13[0];
	char str14[] = "is as fun as taking a nap, or grass.";
	s14 = &str14[0];
	memcpy(s12, s13, 3);
	ft_memcpy(s14, s13, 3);
	printf ("is as fun as taking a nap, or grass. = %s\n", s12);
	printf ("is as fun as taking a nap, or grass. = %s\n", s14);
	printf ("~~~~~~~~~~~~~~~~~~~~\n\n");
	return (0);
}
